#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 01 07:46:00 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.4.zip
